# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Alyf"
# license = ""
# licenselink = ""
description = ""
homepage = "https://alyf.de/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "Raffael Meyer"
  homepage = "https://alyf.de/"
